<!DOCTYPE html>
<html>
<head>
	<title><?php echo $title; ?> - <?php echo $site_title; ?></title>

	<link rel="stylesheet" type="text/css" href="/processwire/site/templates/styles/style.css"></link>
	
	<!-- Webfonts -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:700,300,400' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Merriweather:400,700' rel='stylesheet' type='text/css'>
</head>
<body>



